### PR TITLE
Update xhtml.l

### PR DESCRIPTION
**Pull request by iacore**
Is the missing import intentional?

### CODE REVIEW

**Comment by tankf33der** [comment]
I would not load @lib/http.l implicitly

We have libs @lib.l -> @lib/net.l -> @lib/misc.l -> @lib/http.l -> @lib/xhtml.l -> @lib/form.l

@aw - Reject please

**Comment by iacore** [comment]
i had an old copy of `tut/gui/hello.l` and it only `(load "@lib/xhtml.l")` but uses `(http ...)`.

seems like it's here as well
https://github.com/picolisp/picolisp/blob/dev/doc/hello.l

i have so many questions regarding how i should `load` in picolisp

**Comment by tankf33der** [comment]
this is mirror, no developers.
all fun happens only on IRC, you should try libera.chat, #picolisp

**Comment by aw** [comment]
Sorry @iacore, for pull requests to PicoLisp (pil21) you will need to send them either through the [mailing list](https://www.mail-archive.com/picolisp@software-lab.de/) or on IRC as mentioned by @tankf33der.

**Pull request closed without merging**
